openapi: 3.0.0
info:
  title: Issue Management API
  version: 1.0.0
paths:
  /api/issue:
    post:
      summary: Create a new issue
      description: This endpoint allows a user to create a new issue in the issue management system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: A short, descriptive title for the issue. This field is mandatory. Maximum length is 100 characters.
                  maxLength: 100
                description:
                  type: string
                  description: A detailed explanation of the issue. This field is mandatory. There is no maximum length.
              required:
                - title
                - description
      responses:
        '201':
          description: Issue created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: integer
                    description: The unique identifier for the issue. This field auto increments and is never reused.
                  title:
                    type: string
                    description: The title of the issue. This field has a maximum length of 100 characters.
                  description:
                    type: string
                    description: The description of the issue.
                  status:
                    type: string
                    description: The status of the issue. This field can have one of the following values: 'Open', 'In Progress', 'Closed'.
                  creatorId:
                    type: string
                    format: ObjectId
                    description: The id of the user who created the issue. This is a reference to the user document.
                  assigneeId:
                    type: string
                    format: ObjectId
                    description: The id of the user who is assigned to the issue. This is a reference to the user document.
        '400':
          description: Bad request. User ID must be an integer and non-empty title and description are required.
        '500':
          description: Internal server error.