openapi: 3.0.0
info:
  title: Issue Management System API
  version: 1.0.0
paths:
  /api/comment:
    post:
      summary: Create a new comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                issueId:
                  type: string
                  description: The ID of the issue to which the comment belongs.
                text:
                  type: string
                  description: The text of the comment.
                  maxLength: 500
              required:
                - issueId
                - text
      responses:
        '201':
          description: Comment created successfully.
        '400':
          description: Bad request. User ID must be an integer and greater than 0.
        '404':
          description: Issue not found.
    get:
      summary: Get all comments for a specific issue
      parameters:
        - in: query
          name: issueId
          schema:
            type: string
          required: true
          description: The ID of the issue for which to retrieve comments.
      responses:
        '200':
          description: A list of comments for the specified issue.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The ID of the comment.
                    issueId:
                      type: string
                      description: The ID of the issue to which the comment belongs.
                    text:
                      type: string
                      description: The text of the comment.
                    createdAt:
                      type: string
                      format: date-time
                      description: The date and time when the comment was created.
                    createdBy:
                      type: string
                      description: The username of the user who created the comment.
        '400':
          description: Bad request. Issue ID must be an integer and greater than 0.
        '404':
          description: Issue not found.