openapi: 3.0.0
info:
  title: Issue Management API
  version: 1.0.0
paths:
  /api/issue:
    get:
      summary: Get a list of issues
      parameters:
        - name: title
          in: query
          description: Title of the issue
          required: false
          schema:
            type: string
            maxLength: 100
        - name: status
          in: query
          description: Status of the issue
          required: false
          schema:
            type: string
            enum: [Open, In Progress, Closed]
        - name: assigneeId
          in: query
          description: ID of the user assigned to the issue
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of issues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
    post:
      summary: Create a new issue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueCreate'
      responses:
        '201':
          description: Issue created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
  /api/issue/{id}:
    get:
      summary: Get an issue by ID
      parameters:
        - name: id
          in: path
          description: ID of the issue
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: An issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
    put:
      summary: Update an issue
      parameters:
        - name: id
          in: path
          description: ID of the issue
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IssueUpdate'
      responses:
        '200':
          description: Issue updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
components:
  schemas:
    Issue:
      type: object
      properties:
        _id:
          type: integer
          description: The unique identifier for the issue
        title:
          type: string
          description: The title of the issue
          maxLength: 100
        description:
          type: string
          description: The description of the issue
        status:
          type: string
          description: The status of the issue
          enum: [Open, In Progress, Closed]
        creatorId:
          type: string
          description: The id of the user who created the issue
        assigneeId:
          type: string
          description: The id of the user who is assigned to the issue
    IssueCreate:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
          description: The title of the issue
          maxLength: 100
        description:
          type: string
          description: The description of the issue
        status:
          type: string
          description: The status of the issue
          enum: [Open, In Progress, Closed]
        creatorId:
          type: string
          description: The id of the user who created the issue
        assigneeId:
          type: string
          description: The id of the user who is assigned to the issue
    IssueUpdate:
      type: object
      properties:
        title:
          type: string
          description: The title of the issue
          maxLength: 100
        description:
          type: string
          description: The description of the issue
        status:
          type: string
          description: The status of the issue
          enum: [Open, In Progress, Closed]
        assigneeId:
          type: string
          description: The id of the user who is assigned to the issue
