openapi: 3.0.0
info:
  title: Issue Management API
  version: 1.0.0
paths:
  /api/issue:
    get:
      summary: Get a list of issues
      parameters:
        - name: search
          in: query
          description: Search query
          required: false
          schema:
            type: string
            maxLength: 100
        - name: status
          in: query
          description: Filter by status
          required: false
          schema:
            type: string
            enum: [Open, In Progress, Closed]
        - name: assignedTo
          in: query
          description: Filter by assigned user
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of issues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
    post:
      summary: Create a new issue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Issue'
      responses:
        '201':
          description: The created issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
  /api/issue/{id}:
    get:
      summary: Get a specific issue
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The requested issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
    put:
      summary: Update a specific issue
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Issue'
      responses:
        '200':
          description: The updated issue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Issue'
    delete:
      summary: Delete a specific issue
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: The issue was deleted
components:
  schemas:
    Issue:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          maxLength: 100
        description:
          type: string
        status:
          type: string
          enum: [Open, In Progress, Closed]
        assignedTo:
          type: string
      required:
        - title
        - description